# STOCKS TO PULL DATA ON
STOCK_LIST = ["AAPL", "NVDA", "AMD", "INTL", "GOOG", "GE", "RTX", "HON", "RYCEY", "NOV"]
TECH_STOCKS = ["AAPL", "NVDA", "AMD", "INTL", "GOOG"]
IND_STOCKS = ["GE", "RTX", "HON", "RYCEY", "NOV"]

# PAPER API KEYS
PAPER_API_KEY = "PKE39LILN9SL1FMJMFV7"
PAPER_SECRET_KEY = "TkU7fXH6WhP15MewgWlSnQG5RUoHGOPQ7yqlD6xq"
PAPER_BASE_URL = 'https://paper-api.alpaca.markets'